#!/bin/bash

# excerpted from zclassic/zutil/init-mac.sh

if [ ! -f "$HOME/Library/Application Support/bitcoinz/bitcoinz.conf" ]; then
	echo "Creating bitcoinz.conf"
	mkdir -p "$HOME/Library/Application Support/bitcoinz/"
	echo "rpcuser=username" >> ~/Library/Application\ Support/bitcoinz/bitcoinz.conf
	PASSWORD=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
	echo "rpcpassword=$PASSWORD" >> "$HOME/Library/Application Support/bitcoinz/bitcoinz.conf"
	echo "Complete!"
fi
